version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/dev/:/etc/nginx/conf.d/:ro
    ports:
      - 1337:80
    restart: always
    depends_on:
      - web

volumes:
  postgres_data:
