version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.testing
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
      - ./nginx/testing/:/etc/nginx/conf.d/:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt/:ro
      - /etc/letsencrypt:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - web
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /var/lib/letsencrypt:/var/lib/letsencrypt/:rw
      - /etc/letsencrypt:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  static_volume:
  media_volume:
