# Generated by Django 3.2.3 on 2021-05-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210523_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='accrual_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='accrual_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='accrual_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='asset_turn_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='asset_turn_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='asset_turn_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='beta_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='beta_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='beta_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='cf_debt_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='cf_debt_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='cf_debt_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='composite_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='eve_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='eve_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='eve_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='ext_fin_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='ext_fin_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='ext_fin_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='finance_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='gross_margin_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='gross_margin_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='gross_margin_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='gross_profit_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='gross_profit_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='gross_profit_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='mom_12_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='mom_12_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='mom_12_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='mom_6_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='mom_6_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='mom_6_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='mom_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='pb_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='pb_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='pb_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='pcf_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='pcf_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='pcf_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='pe_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='pe_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='pe_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='profit_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='ps_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='ps_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='ps_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='quality_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='return_asset_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='return_asset_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='return_asset_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='safety_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='value_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='vol_12_ind_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='vol_12_sec_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='vol_12_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='vol_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
