# Generated by Django 3.2.3 on 2021-05-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210523_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='earnings_date',
        ),
    ]
