# Generated by Django 3.2.3 on 2021-05-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_metadata_earnings_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='beta',
        ),
    ]
