# Generated by Django 3.2.3 on 2021-06-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210531_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='company_name_ticker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
