# Generated by Django 3.2.3 on 2021-06-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ticker_company_name_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='company_name_ticker',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
