# Generated by Django 3.1.7 on 2022-02-22 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_crypto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('symbol', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('is_active', models.IntegerField()),
                ('status', models.SlugField(max_length=200)),
            ],
        ),
    ]
