# Generated by Django 3.1.7 on 2022-02-22 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_crypto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrices',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.crypto')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]
