# Generated by Django 3.1.7 on 2022-02-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cryptoprices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoPrices',
        ),
    ]
