# Generated by Django 3.1.7 on 2022-02-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cryptoprices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoprices',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Crypto',
        ),
        migrations.DeleteModel(
            name='CryptoPrices',
        ),
    ]
