# Generated by Django 3.2.3 on 2021-09-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metadescription',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
